apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: project
  name: broadcaster-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: broadcaster
  template:
    metadata:
      labels:
        app: broadcaster
    spec:
      containers:
        - name: broadcaster
          image: IMAGE_PLACEHOLDER_BROADCASTER
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: telegram-apikey
                  key: API_KEY
            - name: NATS_URL
              value: nats://nats.default:4222
