apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./backend-deployment.yaml
- ./backend-service.yaml
- ./broadcaster-deployment.yaml
- ./db-ss.yaml
- ./dbconfig.yaml
- ./frontend-deployment.yaml
- ./frontend-service.yaml
- ./ingress.yaml
- ./persistentvolumeclaim.yaml
- ./persistentvolume.yaml
- ./wikipedia-cronjob.yaml
- ./project-sealed.yaml
- ./broadcaster-sealed.yaml
images:
- name: IMAGE_PLACEHOLDER
  newName: jakousa/dwk-4-gitops-app
  newTag: fdafd7088d04892815ed037cf30ca4f61c7af2f7